"""Seed content ported 1:1 from the validated UI prototype.

TASK_SETS: mission skeleton title -> ordered task payloads (kind + fields).
SCENARIOS: tutor role-play scenarios. SEED_CARDS: starter SRS deck.
"""

from __future__ import annotations

SET_BY_MISSION: dict[str, str] = {
    "Greetings & introductions": "a1a",
    "Meeting new people": "a1a",
    "Numbers & prices": "a1b",
    "Last weekend": "a2a",
    "At the hotel": "a2b",
    "Directions & transport": "a2a",
    "Present perfect basics": "b1",
    "Since vs for": "b1",
    "Job interview English": "b1",
    "Conditionals": "b2",
    "Used to & would": "b2",
}

TASK_SETS: dict[str, list[dict]] = {
    "a1a": [
        {"kind": "mc", "prompt": "Nice to ___ you.", "choices": ["meet", "meets", "meeting", "met"], "answer": 0,
         "why": "After 'to' you need the base form: meet."},
        {"kind": "translate", "prompt": "Translate: “Piacere, mi chiamo Marco.”",
         "accepted": ["nice to meet you, my name is marco", "nice to meet you, im marco", "nice to meet you, i am marco"],
         "answerText": "Nice to meet you, my name is Marco.",
         "why": "'Mi chiamo' = my name is (or I'm)."},
        {"kind": "gap", "prompt": "Where ___ you from?", "choices": ["are", "is", "do", "does"], "answer": 0,
         "why": "Origin uses 'to be': Where are you from?"},
        {"kind": "order", "prompt": "Build the sentence:", "words": ["This", "is", "my", "friend", "David."],
         "why": "English word order is subject-verb-object."},
        {"kind": "listening", "say": "See you tomorrow at nine.", "accepted": ["see you tomorrow at nine"],
         "why": "'At' for clock times: at nine, at noon."},
        {"kind": "speaking", "say": "Nice to meet you. My name is Marco."},
    ],
    "a1b": [
        {"kind": "mc", "prompt": "The shirt costs £25. You read it:", "choices": ["twenty-five pounds", "twenty five pound", "twenty-five pound", "fifty pounds"], "answer": 0,
         "why": "Currency words take the plural above one: pounds."},
        {"kind": "translate", "prompt": "Translate: “Quanto costa questo biglietto?”",
         "accepted": ["how much is this ticket", "how much does this ticket cost"],
         "answerText": "How much is this ticket?",
         "why": "Never 'How much costs…?'"},
        {"kind": "gap", "prompt": "I'd like ___ apples, please.", "choices": ["three", "third", "a three", "thirds"], "answer": 0,
         "why": "Cardinal numbers count; ordinals order."},
        {"kind": "order", "prompt": "Build the sentence:", "words": ["Can", "I", "pay", "by", "card,", "please?"],
         "why": "Payment method takes 'by': by card, by cash."},
        {"kind": "listening", "say": "That will be twelve euros and fifty cents.",
         "accepted": ["that will be twelve euros and fifty cents"],
         "why": "Or 'twelve fifty' in fast speech."},
        {"kind": "speaking", "say": "Can I pay by card, please?"},
    ],
    "a2a": [
        {"kind": "mc", "prompt": "Last weekend I ___ my grandparents.", "choices": ["visited", "have visited", "visit", "was visited"], "answer": 0,
         "why": "Finished time ('last weekend') forces the past simple."},
        {"kind": "gap", "prompt": "We ___ to the cinema on Saturday.", "choices": ["went", "gone", "was", "did"], "answer": 0,
         "why": "Irregular past: go -> went; 'gone' needs have/has."},
        {"kind": "translate", "prompt": "Translate: “Non sono uscito ieri sera.”",
         "accepted": ["i didn't go out last night", "i did not go out last night"],
         "answerText": "I didn't go out last night.",
         "why": "Negative past: didn't + base form."},
        {"kind": "order", "prompt": "Build the question:", "words": ["What", "did", "you", "do", "on", "Sunday", "morning?"],
         "why": "Past questions: did + subject + base form."},
        {"kind": "listening", "say": "The train left ten minutes ago.", "accepted": ["the train left ten minutes ago"],
         "why": "'Ago' sits after the time and takes past simple."},
        {"kind": "speaking", "say": "The train left ten minutes ago."},
    ],
    "a2b": [
        {"kind": "mc", "prompt": "Do you have a reservation ___ the name Rossi?", "choices": ["by", "under", "at", "with"], "answer": 1,
         "why": "Bookings are made 'under' a name."},
        {"kind": "translate", "prompt": "Translate: “Ho prenotato una doppia per tre notti.”",
         "accepted": ["i booked a double room for three nights", "i have booked a double room for three nights", "i reserved a double room for three nights"],
         "answerText": "I booked a double room for three nights.",
         "why": "'Una doppia' = a double room; duration with 'for'."},
        {"kind": "order", "prompt": "Build the question:", "words": ["Have", "you", "ever", "stayed", "with", "us", "before?"],
         "why": "Present perfect question: Have + subject + ever + participle."},
        {"kind": "gap", "prompt": "Breakfast is included ___ the rate.", "choices": ["in", "on", "at", "of"], "answer": 0,
         "why": "Fixed collocation: included in."},
        {"kind": "listening", "say": "Your room is on the third floor, room three oh five.",
         "accepted": ["your room is on the third floor room 305", "your room is on the third floor room three hundred and five", "your room is on the third floor room three oh five"],
         "why": "Floors take 'on'; room numbers go digit by digit."},
        {"kind": "speaking", "say": "I'd like a double room for three nights, please."},
    ],
    "b1": [
        {"kind": "mc", "prompt": "I ___ in Milan since 2019.", "choices": ["have lived", "live", "lived", "am living"], "answer": 0,
         "why": "'Since' anchors the present perfect."},
        {"kind": "mc", "prompt": "___ you ever eaten sushi?", "choices": ["Have", "Did", "Are", "Do"], "answer": 0,
         "why": "ever/never experiences take the present perfect."},
        {"kind": "translate", "prompt": "Translate: “Non ho mai visto quel film.”",
         "accepted": ["i have never seen that film", "i've never seen that film", "i have never watched that film"],
         "answerText": "I have never seen that film.",
         "why": "never + present perfect in English."},
        {"kind": "order", "prompt": "Build the sentence:", "words": ["She", "has", "worked", "here", "for", "six", "years."],
         "why": "Duration takes 'for'; a start point takes 'since'."},
        {"kind": "mc", "prompt": "I ___ him yesterday.", "choices": ["saw", "have seen", "seen", "see"], "answer": 0,
         "why": "'Yesterday' is a finished time: past simple."},
        {"kind": "speaking", "say": "I have never seen that film before."},
    ],
    "b2": [
        {"kind": "mc", "prompt": "If I ___ more time, I would learn Japanese.", "choices": ["had", "have", "will have", "would have"], "answer": 0,
         "why": "Second conditional: if + past, would + base form."},
        {"kind": "gap", "prompt": "I ___ to smoke, but I quit last year.", "choices": ["used", "use", "am used", "would"], "answer": 0,
         "why": "'Used to' = past habit that stopped."},
        {"kind": "translate", "prompt": "Translate: “Se fossi ricco, viaggerei di più.”",
         "accepted": ["if i were rich i would travel more", "if i was rich i would travel more"],
         "answerText": "If I were rich, I would travel more.",
         "why": "'Were' is preferred for all persons in formal English."},
        {"kind": "order", "prompt": "Build the sentence:", "words": ["She", "used", "to", "live", "in", "Rome", "when", "she", "was", "young."],
         "why": "'Used to + base form' for past states."},
        {"kind": "listening", "say": "I wish I had started sooner.", "accepted": ["i wish i had started sooner"],
         "why": "Past regret: I wish + past perfect."},
        {"kind": "speaking", "say": "If I were rich, I would travel more."},
    ],
}

SCENARIOS: list[dict] = [
    {"id": "airport", "name": "Airport check-in", "persona": "Amelia", "role": "check-in agent", "level": "A2",
     "description": "Check in for an evening flight to London: passport, bags, seat preference, boarding pass."},
    {"id": "interview", "name": "Job interview", "persona": "Daniel", "role": "hiring manager", "level": "B1",
     "description": "Talk about your background, strengths on a team, and where you see yourself in five years."},
    {"id": "restaurant", "name": "Ordering at a restaurant", "persona": "Sofia", "role": "waitress", "level": "A2",
     "description": "Get a table, order drinks and food, and settle the bill."},
]

SEED_CARDS: list[dict] = [
    {"front": "since vs for", "back": "since + starting point (since 2019); for + duration (for six years)", "example": "I've lived here since 2019."},
    {"front": "information", "back": "Uncountable — never 'informations'. Use 'pieces of information'.", "example": "Let me give you some information."},
    {"front": "depend on", "back": "'Depend' always takes 'on', never 'of'.", "example": "It depends on the weather."},
    {"front": "I am 25 years old", "back": "Age uses 'to be', not 'to have' (calque from Italian).", "example": "She is thirty years old."},
    {"front": "a / an", "back": "'An' before a vowel sound: an email, an hour, an umbrella.", "example": "I'll send you an email."},
    {"front": "didn't + base form", "back": "After did/didn't the verb stays in base form.", "example": "I didn't go out last night."},
    {"front": "take a photo", "back": "Collocation: take a photo, make a mistake.", "example": "Can I take a photo here?"},
    {"front": "used to + base form", "back": "Past habit that stopped. 'I am used to' = being accustomed.", "example": "I used to live in Rome."},
    {"front": "present perfect: experience", "back": "ever/never + have + past participle for life experiences.", "example": "Have you ever eaten sushi?"},
    {"front": "explain to someone", "back": "'Explain' needs 'to' before a person.", "example": "Let me explain it to you."},
]
